//! Modifier — applies changes to the codebase

use super::types::*;
use std::fs;
use std::path::Path;
use tracing::info;

/// Apply a modification plan
pub fn apply_plan(plan: &ModifyPlan, source_dir: &Path) -> Result<(), ModifyError> {
    info!("Applying plan with {} file changes", plan.files.len());

    for file in &plan.files {
        match file.change_type {
            ChangeType::Create => {
                create_file(file, source_dir)?;
            }
            ChangeType::Modify => {
                modify_file(file, source_dir)?;
            }
            ChangeType::Delete => {
                delete_file(file, source_dir)?;
            }
        }
    }

    Ok(())
}

fn create_file(file: &FileChange, source_dir: &Path) -> Result<(), ModifyError> {
    let path = source_dir.join(&file.path);
    fs::create_dir_all(path.parent().unwrap())?;

    // The actual content will be generated by the LLM
    // This is a placeholder that gets replaced
    let content = format!(
        "// Auto-generated by ClawReform self-modification\n// Request: {}\n\n{}",
        file.diff_preview,
        generate_placeholder_content(&file.path)
    );

    fs::write(&path, content)?;
    info!("Created: {:?}", file.path);

    Ok(())
}

fn modify_file(file: &FileChange, source_dir: &Path) -> Result<(), ModifyError> {
    let path = source_dir.join(&file.path);

    if !path.exists() {
        return Err(ModifyError::Modification(format!(
            "File not found: {:?}",
            file.path
        )));
    }

    // Apply the diff (simplified version)
    // In practice, this would use a proper diff library
    let content = fs::read_to_string(&path)?;
    let new_content = apply_diff(&content, &file.diff_preview);

    fs::write(&path, new_content)?;
    info!("Modified: {:?}", file.path);

    Ok(())
}

fn delete_file(file: &FileChange, source_dir: &Path) -> Result<(), ModifyError> {
    let path = source_dir.join(&file.path);

    if path.exists() {
        fs::remove_file(&path)?;
        info!("Deleted: {:?}", file.path);
    }

    Ok(())
}

fn apply_diff(original: &str, diff: &str) -> String {
    // Simplified: in practice, use a proper diff library like diffy
    // For now, just append the diff as a comment
    format!(
        "{}\n\n// Self-modification applied:\n// {}",
        original,
        diff.lines().collect::<Vec<_>>().join("\n// ")
    )
}

fn generate_placeholder_content(path: &Path) -> String {
    match path.extension().and_then(|e| e.to_str()) {
        Some("rs") => "// TODO: Implement\n".to_string(),
        Some("md") => "# TODO: Document\n".to_string(),
        Some("toml") => "# TODO: Configure\n".to_string(),
        _ => "".to_string(),
    }
}
